# version: '3.8'

services:
  api-gateway:
    build: ./services/api-gateway
    image: ${CR_PREFIX}api-gateway:latest
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - RUN_MODE=${RUN_MODE}
      - AUCTION_SERVICE_HEROKU_URL=${AUCTION_SERVICE_HEROKU_URL}
      - USER_SERVICE_HEROKU_URL=${USER_SERVICE_HEROKU_URL}
    ports:
      - "4000:4000"
    networks:
      - auction-network

  auction-service:
    build: ./services/auction-service
    image: ${CR_PREFIX}auction-service:latest
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - RUN_MODE=${RUN_MODE}
      - API_GATEWAY_HEROKU_URL=${API_GATEWAY_HEROKU_URL}
      - AZURE_BID_EMAIL_FUNCTION=${AZURE_BID_EMAIL_FUNCTION}
    ports:
       - "7070:7070"
    depends_on:
      - api-gateway
    networks:
      - auction-network

  user-service:
    build: ./services/user-service
    image: ${CR_PREFIX}user-service:latest
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - api-gateway
    networks:
      - auction-network

  frontend:
    build: ./services/frontend
    image: ${CR_PREFIX}frontend:latest
    environment:
      - VITE_RUN_MODE=${RUN_MODE}
      - VITE_API_GATEWAY_HEROKU_URL=${API_GATEWAY_HEROKU_URL}
    ports:
      - "80:5173"
    depends_on:
      - api-gateway
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge