# version: '3.8'

services:
  api-gateway:
    build: ./services/api-gateway
    image: ${CR_PREFIX}api-gateway:latest
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - auction-service
    networks:
      - auction-network

  auction-service:
    build: ./services/auction-service
    image: ${CR_PREFIX}auction-service:latest
    env_file:
      - ./.env
    ports:
      - "7070:7070"
    networks:
      - auction-network

  user-service:
    build: ./services/user-service
    image: ${CR_PREFIX}user-service:latest
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - auction-network

  frontend:
    build: ./services/frontend
    image: ${CR_PREFIX}frontend:latest
    ports:
      - "80:80"
#    volumes:
#      - ./services/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge