# version: '3.8'

services:
  api-gateway:
    build: ./services/api-gateway
    env_file:
      - ./.env
      - ./services/api-gateway/.env
    ports:
      - "4000:4000"
    restart: always
    networks:
      - auction-network

  auction-service:
    build: ./services/auction-service
    env_file:
      - ./.env
      - ./services/auction-service/.env
    ports:
      - "7070:7070"
    restart: always
    depends_on:
      - api-gateway
    networks:
      - auction-network

  user-service:
    build: ./services/user-service
    env_file:
      - ./.env
      - ./services/user-service/.env
    ports:
      - "8080:8080"
    depends_on:
      - api-gateway
    restart: always
    networks:
      - auction-network

  frontend:
    build: ./services/frontend
    env_file:
      - ./.env
      - ./services/frontend/.env
    ports:
      - "80:5173"
    depends_on:
      - api-gateway
    restart: always
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge