version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service


  user-service:
    build: ./services/user-service
    ports:
      - "6000:6000"