version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
    networks:
      - auction-network


  user-service:
    build: ./services/user-service
    env_file:
      - ./services/user-service/.env
    ports:
      - "8080:8080"
    networks:
      - auction-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge