version: '3.8'

services:
  api-gateway:
    build: ./services/api-gateway
    image: ${CR_PREFIX}api-gateway:latest
    ports:
      - "4000:4000"
    depends_on:
      - user-service
    networks:
      - auction-network


  user-service:
    build: ./services/user-service
    image: ${CR_PREFIX}user-service:latest
    env_file:
      - ./services/user-service/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_KEY=${DATABASE_KEY}
      - SECRET_KEY=${JWT_KEY}
    ports:
      - "8080:8080"
    networks:
      - auction-network

  frontend:
    build: ./services/frontend
    image: ${CR_PREFIX}frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./services/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge