name: Deploy to Azure Container App via ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual deployment

env:
  CR_USERNAME: ${{ secrets.ACR_USERNAME }}
  CR_TOKEN: ${{ secrets.ACR_PASSWORD }}
  CR_PREFIX: ${{ secrets.ACR_LOGIN_SERVER }}

jobs:
  build-and-test:
    name: Build and Test Microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Microservices with Docker Compose
        run: |
          echo "Building microservices..."
          docker compose --env-file .env -f docker-compose.yml build

      - name: Run Tests
        run: |
          echo "Running tests for each microservices..."
          docker compose --env-file .env -f docker-compose.yml -f docker-compose-test.yml up --abort-on-container-exit

      - name: Stop and Clean Up After Testing
        run: docker compose --env-file .env -f docker-compose.yml down -v

  push-images:
    name: Push Docker Images to ACR
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo ${{ env.CR_TOKEN }} | docker login ${{ env.CR_PREFIX }} --username ${{ env.CR_USERNAME }} --password-stdin


      - name: Build and Push Images to ACR
        run: |
          export CR_PREFIX=${{ env.CR_PREFIX }}
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
