name: Build, Test and Deploy to Heroku
 
on:
  push:
    branches:
#      - main
  workflow_dispatch:  # Allows manual deployment
 
env:
  SUPABASE_URL: ${{secrets.SUPABASE_URL}}
  SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
  JWT_KEY: ${{secrets.JWT_KEY}}
  AUCTION_SERVICE_HEROKU_URL: ${{secrets.AUCTION_SERVICE_HEROKU_URL}}
  USER_SERVICE_HEROKU_URL: ${{secrets.USER_SERVICE_HEROKU_URL}}
  API_GATEWAY_HEROKU_URL: ${{secrets.API_GATEWAY_HEROKU_URL}}

jobs:
  build-and-test:
    name: Build and Test Microservices
    runs-on: ubuntu-latest
    env:
      CR_PREFIX: ""
      RUN_MODE: docker
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Build Microservices with Docker Compose
        run: |
          echo "Building microservices..."
          docker compose -f docker-compose.yml build
 
      - name: Run Tests
        run: |
          echo "Running tests for each microservices..."
          docker compose -f docker-compose.yml -f docker-compose-test.yml up --abort-on-container-exit
 
      - name: Stop and Clean Up After Testing
        run: |
          docker compose -f docker-compose.yml down -v
 
  push-images:
    name: Push Docker Images to GHCR as Backup
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      RUN_MODE: heroku
      CR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      CR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo ${{env.CR_TOKEN}} | docker login ghcr.io -u ${{env.CR_USERNAME}} --password-stdin

      - name: Build and Push Images to GHCR
        run: |
          export CR_PREFIX="ghcr.io/${{env.CR_USERNAME}}/"
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
 
  deploy-to-heroku:
    name: deploy Images to Heroku
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      HEROKU_REGISTRY_PREFIX: registry.heroku.com
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}}

      HEROKU_FRONTEND_APP_NAME: ${{secrets.HEROKU_FRONTEND_APP_NAME}}
      HEROKU_API_GATEWAY_APP_NAME: ${{secrets.HEROKU_API_GATEWAY_APP_NAME}}
      HEROKU_AUCTION_SERVICE_APP_NAME: ${{secrets.HEROKU_AUCTION_SERVICE_APP_NAME}}
      HEROKU_USER_SERVICE_APP_NAME: ${{secrets.HEROKU_USER_SERVICE_APP_NAME}}

      RUN_MODE: heroku
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
 
      - name: Login to docker
        run: |
          echo ${{ env.HEROKU_API_KEY }} | docker login --username ${{env.HEROKU_USERNAME}} --password-stdin registry.heroku.com
 
      - name: Authenticate with Heroku
        run: |
          echo "machine api.heroku.com login ${{env.HEROKU_USERNAME}} password ${{ env.HEROKU_API_KEY }}" > ~/.netrc
          echo "machine git.heroku.com login ${{env.HEROKU_USERNAME}} password ${{ env.HEROKU_API_KEY }}" >> ~/.netrc
          chmod 600 ~/.netrc
          heroku auth:token
          heroku auth:whoami
 
      # build frontend service as web
      - name: Build Services
        run: |
          echo "Building microservices..."
          docker compose -f docker-compose.yml build

      - name: Tag Images
        run: |
          echo "Retag images..."
          docker tag frontend ${HEROKU_REGISTRY_PREFIX}/${HEROKU_FRONTEND_APP_NAME}/web
          docker tag api-gateway ${HEROKU_REGISTRY_PREFIX}/${HEROKU_API_GATEWAY_APP_NAME}/web
          docker tag auction-service ${HEROKU_REGISTRY_PREFIX}/${HEROKU_AUCTION_SERVICE_APP_NAME}/web
          docker tag user-service ${HEROKU_REGISTRY_PREFIX}/${HEROKU_USER_SERVICE_APP_NAME}/web

      - name: Push Images
        run: |
          echo "Push images..."
          docker push ${HEROKU_REGISTRY_PREFIX}/${HEROKU_FRONTEND_APP_NAME}/web
          docker push ${HEROKU_REGISTRY_PREFIX}/${HEROKU_API_GATEWAY_APP_NAME}/web
          docker push ${HEROKU_REGISTRY_PREFIX}/${HEROKU_AUCTION_SERVICE_APP_NAME}/web
          docker push ${HEROKU_REGISTRY_PREFIX}/${HEROKU_USER_SERVICE_APP_NAME}/web

#      - name: Update Environment Variables for each Heroku app
#        run: |
#          heroku config:set -a ${{env.HEROKU_FRONTEND_APP_NAME}} \
#                               API_GATEWAY_HEROKU_URL=${{secrets.API_GATEWAY_HEROKU_URL}}
#
#          heroku config:set -a ${{env.HEROKU_API_GATEWAY_APP_NAME}} \
#                               SUPABASE_URL=${{secrets.SUPABASE_URL}} \
#                               SUPABASE_KEY=${{secrets.SUPABASE_KEY}} \
#                               JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}} \
#                               AUCTION_SERVICE_HEROKU_URL=${{secrets.AUCTION_SERVICE_HEROKU_URL}} \
#                               USER_SERVICE_HEROKU_URL=${{secrets.USER_SERVICE_HEROKU_URL}}
#
#
#          heroku config:set -a ${{env.HEROKU_AUCTION_SERVICE_APP_NAME}} \
#                               SUPABASE_URL=${{secrets.SUPABASE_URL}} \
#                               SUPABASE_KEY=${{secrets.SUPABASE_KEY}} \
#                               JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}
#
#
#          heroku config:set -a ${{env.HEROKU_USER_SERVICE_APP_NAME}} \
#                               SUPABASE_URL=${{secrets.SUPABASE_URL}} \
#                               SUPABASE_KEY=${{secrets.SUPABASE_KEY}} \
#                               JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}
                          
 
      - name: Release pushed images to Heroku
        run: |
          heroku container:release web -a ${{env.HEROKU_FRONTEND_APP_NAME}}
          heroku container:release web -a ${{env.HEROKU_API_GATEWAY_APP_NAME}}
          heroku container:release web -a ${{env.HEROKU_AUCTION_SERVICE_APP_NAME}}
          heroku container:release web -a ${{env.HEROKU_USER_SERVICE_APP_NAME}}

      - name: Scale dynos
        run: |
          heroku ps:scale web=1 -a ${{env.HEROKU_FRONTEND_APP_NAME}}
          heroku ps:scale web=1 -a ${{env.HEROKU_API_GATEWAY_APP_NAME}}
          heroku ps:scale web=1 -a ${{env.HEROKU_AUCTION_SERVICE_APP_NAME}}
          heroku ps:scale web=1 -a ${{env.HEROKU_USER_SERVICE_APP_NAME}}
